site_name: Git Notları
site_url: https://github.com/buravc
theme:
  name: material

nav:
  - index.md
  - Temeller:
    - "Repository Olusturmak": temeller/repository-olusturmak.md
    - "Branch Olusturmak": temeller/branch-olusturmak.md
    - "Commit History": temeller/commit-history.md
    - "Branch Merge / Merge Commit": temeller/merge-commit.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences