site_name: Git Notları
site_url: https://github.com/buravc
theme:
  name: material

nav:
  - index.md
  - Temeller:
    - "Repository Olusturmak": temeller/repository-olusturmak.md
    - "Branch Olusturmak": temeller/branch-olusturmak.md
    - "Bir Commit Aslinda Nedir?": temeller/bir-commit-aslinda-nedir.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences